### PR TITLE
Make module compatible with newer versions of React

### PR DESCRIPTION
**Pull request by rikukissa**
* Replace this.transferPropsTo with React.createElement - https://gist.github.com/sebmarkbage/a6e220b7097eb3c79ab7
* Replace React.DOM.input and React.DOM.textarea with strings

Works with React 0.13.1. These changes might not be backwards compatible with older versions of React so a major version change might be in place.

### CODE REVIEW

**Comment by rikukissa** [comment]
Any comments?

**Comment by yaycmyk** [comment]
@rikukissa Could you rebase please? Sorry for the delay on our end.

**Comment by rikukissa** [comment]
Done and done!

**Comment by yaycmyk** [comment]
Hmm, still says there's a merge conflict @rikukissa

**Comment by rikukissa** [comment]
Oh! I think I failed somehow. Should be fine now :)

**Comment by yaycmyk** [comment]
Landed in https://github.com/enigma-io/react-input-placeholder/commit/1e1e2685bd3236c909f59c593091edef4e471853, thanks for your contribution @rikukissa

**Pull request closed without merging**
